USE Superheroes
GO


INSERT INTO dbo.Gadget (Gadget_Name, Gadget_Desc)
VALUES ('Magnetic Shield', 'Weapon\Equipment used by Captain America')
, ('Ultimate Nullifier', 'Weapon\Equipment used by Thanos')
, ('Infinity Gauntlet', 'Weapon\Equipment used by Thanos')
, ('Infinity Stones', 'Weapon\Equipment used by Thanos')
, ('Boomerang', 'Weapon\Equipment used by Captain Boomerang (enemy of the Flash)')
, ('Encephalo Gun', 'Weapon\Equipment used by Mister Fantastic')
, ('Cosmic Treadmill', 'Weapon\Equipment used by the Flash')
, ('Plastimold', 'Weapon\Equipment used by Lois Lane')
, ('Bat-tector', 'Weapon\Equipment used by Batman')
, ('Gambit Cards', 'Weapon\Equipment used by Gambit (X-Men)')
, ('Absorbascon', 'Weapon\Equipment used by Hawkgirl\Hawkman')
, ('Spider-wave Transmitter', 'Weapon\Equipment used by Spiderman')
, ('Anti-Magnetic Inverter', 'Weapon\Equipment used by Spiderman')
, ('Roller Skates', 'Weapon\Equipment used by Iron Man')
, ('Truth Chamber', 'Weapon\Equipment used by Batman')
, ('Arrows', 'Weapon\Equipment used by Green Arrow')
, ('Shark Repellent Spray', 'Weapon\Equipment used by Batman')
, ('Power Ring', 'Weapon\Equipment used by Green Lantern')
, ('Hammer', 'Weapon\Equipment used by Thor')
, ('Fiddle', 'Weapon\Equipment used by The Fiddler')
, ('Surfboard', 'Weapon\Equipment used by the Silver Surfer')
, ('Catapult', 'Weapon\Equipment used by Ant-Man')
, ('Witchblade', 'Weapon\Equipment used by Sara Pezzini (Top Cow Comic Universe)')
, ('Helmet of Fate\Helmet of Nabu', 'Weapon\Equipment used by DC Universe')
, ('Billy Club', 'Weapon\Equipment used by Daredevil')
, ('Element Gun', 'Weapon\Equipment used by Star-Lord')
, ('Eye of Agamotto', 'Weapon\Equipment used by Doctor Strange')
, ('Whip', 'Weapon\Equipment used by Catwoman')
, ('Umbrella', 'Weapon\Equipment used by Penguin')

